### ISSUE TITLE
Background pic on edit page

### ISSUE THREAD

**Issue by Kalaborative** [Kalaborative/StageR#1]
- [ ] Bg picture on `edit.html` needs to be set to **stretch**, not **tiled**
- [x] Update changelog to include responsive edit pages

**Comment by aruna09** [comment]
I'll take this one

**Comment by aruna09** [comment]
Will it be okay if the changes are made in the edit.css file instead of edit.html file?

**Comment by Kalaborative** [comment]
@ArunaMaurya221B, yes! That's what I meant, sorry. Edit.html styles are based on edit.css :-)
