### ISSUE TITLE
Would like more images to choose from

### ISSUE THREAD

**Issue by Kalaborative** [Kalaborative/StageR#10]
- [x] **Add more animal images or substitute a whole image set for more variety.**

Currently, there are only about _12 minimalistic animal images_ to randomly assign to users. We want to know if we could have more or simply use a different, but larger set of images!

Thanks!

**Comment by Lahirutech** [comment]
I will try to work with the issue.This is my first attempt on Open source.A bit curious!!

**Comment by Lahirutech** [comment]
can you please help me to find the code which randomly assigns the user images :)

**Comment by Kalaborative** [comment]
Sure @Lahirutech 👍 
In `app.py`, it's on line **15** where image names are in a list stored in `animals` variable and line **27** where a random animal is chosen and assigned to variable `inputan`.
HTH

**Comment by Lahirutech** [comment]
Thank you.Around how many images do you want in the new update :)

**Comment by Kalaborative** [comment]
Let's try to shoot for 20! As many as you like really, as long as it's more than 12 :)

**Comment by Lahirutech** [comment]
Ok great I am working on it.. :-)

**Comment by Lahirutech** [comment]
I have completed the work.When I try to push the edited code this error came.
remote: Permission to Kalaborative/StageR.git denied to Lahirutech.
fatal: unable to access 'https://github.com/Kalaborative/StageR.git/': The requested URL returned error: 403
Can you please let me know How to solve this issue? 

![upload to git](https://user-images.githubusercontent.com/19344653/31486296-a1501958-af54-11e7-81f9-eec1b8951627.jpg)

**Comment by Lahirutech** [comment]
I am new to git I think I sent a pull request successfully!!! :)

**Comment by Kalaborative** [comment]
@Lahirutech Merged, thanks :+1:
