### ISSUE TITLE
Main page: switch out icon on "like" to "clap"

### ISSUE THREAD

**Issue by Kalaborative** [Kalaborative/StageR#11]
- [ ] Since users can "like" a performer more than once, we want to instead have the clap functionality by changing the image from a **fire** icon to a **clap** icon.

**Comment by Kalaborative** [comment]
Issue is fixed thanks to PR by xDidier

**Comment by Kalaborative** [comment]
Reopened due to the following:
- [ ] **CSS is using the icons from Bootstrap v3.3.6 , this is causing the icon to not display at all.** Is there a possible CDN to link the glyphicons?
- [ ]  Change was made to the `index.html` file, but also need that **same change reflected in `public.html`**

Thanks!

**Comment by Kalaborative** [comment]
Edit: can't seem to find that glyphicon at all? Where did you find this? 
Might be better just to settle for a heart glyphicon instead!

**Comment by Utkarshbhimte** [comment]
@Kalaborative How about just adding this emoji: 👏 , why look for a glyphicon at all?

**Comment by Kalaborative** [comment]
@Utkarshbhimte We could do that, though you'd have to do the same for the other button as well

**Comment by AndrewUsher** [comment]
Do you still need someone to work on this?

**Comment by Kalaborative** [comment]
Yeah, hasn't been taken in a while, and would be nice :-)

**Comment by Kalaborative** [comment]
Issue is taken care of!
